### ISSUE TITLE
Implement HAVING clause for SELECT

### ISSUE THREAD

**Issue by ScottyFillups** [lumina-tech/gOOQ#4]
gOOQ's `SELECT` currently does not support the `HAVING` clause: https://github.com/lumina-tech/gOOQ/blob/master/pkg/gooq/select.go#L285

Here is a code snippet that currently panics, because `HAVING` is not implemented:

```go
gooq.Select(gooq.Count(model.Person.ID)).
	GroupBy(model.Person.BirthYear).
	Having(model.Person.BirthYear.Gt(gooq.String("1995")))
```

**Comment by ppong** [comment]
This is now implemented
